### ISSUE TITLE
Carthage + Xcode 10 : Task failed with exit code 65 

### ISSUE THREAD

**Issue by daniv3r** [matsune/MidiParser#2]
When run 'carthage update --platform iOS on your project'

Get this :

"Building scheme "MidiParser iOS" in MidiParser.xcworkspace
Build Failed/Task failed with exit code 65"

**Comment by matsune** [comment]
I just fixed and released version 0.2 .
Please retry `carthage update --platform iOS`

**Comment by daniv3r** [comment]
Thanks!

**Comment by ajmalhsn** [comment]
MIdi  Parser error on Xcode 12.0. I am receiving the error that it was compiled by Swift 5.2.4 and is not compatible with swift 5.3. Changing the compiler version in my project also doesn't fix this.

**Comment by dejawooh** [comment]
Looks like updating to Xcode 12 makes the library incompatible. not able to find any workaround.
